---
version: '3.1'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_data:/var/log/rabbitmq
    #networks:
    #  - rabbitmq_go_net
#networks:
#  rabbitmq_go_net:
#    driver: bridge

volumes:
  rabbitmq_data:
